### PR TITLE
Add support for Swift 4.2

### PR DESCRIPTION
**Pull request by iamweiqian**

### CODE REVIEW

**Comment by iamweiqian** [comment]
> HI @iamweiqian, thank you so much for your contribution, could you fix the issue please? Once it's done, I will merge it, cheers

Which version of Xcode are you using?

**Comment by iamweiqian** [comment]
> “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.```

Which version of Xcode are you using?

**Comment by jeantimex** [comment]
I am using Version 10.0

**Comment by jeantimex** [comment]
I have migrated the project to 4.2 :) Thanks for your contribution!

**Pull request closed without merging**
